"Streaming, redes sociales y conciertos: construcción empírica del éxito de un artista musical"
Autora Silvana Contreras
Mayo 2026

In [52]:
# !pip install pandas numpy matplotlib seaborn scikit-learn jupyter

In [1]:
import pandas as pd
import numpy as np

# levanto dataset

In [3]:
from pathlib import Path
import pandas as pd

# df = pd.read_csv("dataset_4913_53.csv")
df = pd.read_csv("dataset_7000_53.csv")

print("Dimensiones:", df.shape)

Dimensiones: (7000, 53)

# dimensiones variables

In [7]:
# ============================================================
# Paso 2. Agrupación conceptual de variables
# Construcción de diccionario de variables
# ============================================================

id_cols = [
    "chartmetric_id",
    "artist_name"
]

metadata_cols = [
    "country",
    "country_short",
    "pronoun_title",
    "pronoun_short",
    "record_label",
    "major_record_label",
    "primary_genre",
    "genre_short",
    "band",
    "muerto_disuelto"
]

streaming_cols = [
    "sp_followers",
    "sp_monthly_listeners",
    "sp_popularity",
    "deezer_fans",
    "shazam_count",
    "pandora_lifetime_streams",
    "pandora_lifetime_stations_added"
]

playlist_cols = [
    "sp_playlist_total_reach",
    "num_sp_editorial_playlists",
    "num_sp_playlists",
    "sp_editorial_playlist_total_reach",
    "num_am_editorial_playlists",
    "num_am_playlists",
    "num_de_editorial_playlists",
    "num_de_playlists",
    "de_playlist_total_reach",
    "de_editorial_playlist_total_reach",
    "num_az_editorial_playlists",
    "num_az_playlists",
    "num_yt_editorial_playlists",
    "num_yt_playlists",
    "yt_playlist_total_reach"
]

social_cols = [
    "ins_followers",
    "twitter_followers",
    "tiktok_followers",
    "tiktok_likes",
    "tiktok_top_video_views",
    "tiktok_top_video_comments",
    "tiktok_track_posts"
]

youtube_cols = [
    "ycs_subscribers",
    "ycs_views",
    "youtube_daily_video_views",
    "youtube_monthly_video_views"
]

live_cols = [
    "n_shows_24_25",
    "n_shows_with_capacity_24_25",
    "capacity_24_25",
    "avg_venue_capacity_24_25",
    "n_cities_24_25",
    "n_countries_24_25",
    "shows_per_country_24_25",
    "off_cycle"
]

# Diccionario de dimensiones
column_groups = {
    "identificacion": id_cols,
    "metadata": metadata_cols,
    "streaming": streaming_cols,
    "playlists": playlist_cols,
    "redes_sociales": social_cols,
    "youtube": youtube_cols,
    "live_events": live_cols
}

# ============================================================
# Tabla auxiliar con identidad conceptual de cada variable
# ============================================================

variable_dimension = []

for dimension, cols in column_groups.items():
    for col in cols:
        variable_dimension.append({
            "variable": col,
            "dimension": dimension
        })

df_variable_dimension = pd.DataFrame(variable_dimension)

# ============================================================
# Control de cobertura de columnas
# ============================================================

grouped_cols = df_variable_dimension["variable"].tolist()

cols_in_groups_not_in_df = sorted(set(grouped_cols) - set(df.columns))
cols_in_df_not_in_groups = sorted(set(df.columns) - set(grouped_cols))

print("Columnas del df:", df.shape[1])
print("Columnas agrupadas:", len(grouped_cols))
print("Columnas agrupadas que no están en df:", cols_in_groups_not_in_df)
print("Columnas del df no agrupadas:", cols_in_df_not_in_groups)

# ============================================================
# Resumen por dimensión
# ============================================================

resumen_dimensiones = (
    df_variable_dimension
    .groupby("dimension", as_index=False)
    .agg(n_variables=("variable", "count"))
    .sort_values("n_variables", ascending=False)
)

display(resumen_dimensiones)

# ============================================================
# Vista del diccionario de variables
# ============================================================

display(df_variable_dimension)

Columnas del df: 53
Columnas agrupadas: 53
Columnas agrupadas que no están en df: []
Columnas del df no agrupadas: []

        dimension  n_variables
3       playlists           15
2        metadata           10
1     live_events            8
5       streaming            7
4  redes_sociales            7
6         youtube            4
0  identificacion            2

                             variable       dimension
0                      chartmetric_id  identificacion
1                         artist_name  identificacion
2                             country        metadata
3                       country_short        metadata
4                       pronoun_title        metadata
5                       pronoun_short        metadata
6                        record_label        metadata
7                  major_record_label        metadata
8                       primary_genre        metadata
9                         genre_short        metadata
10                               band        metadata
11                    muerto_disuelto        metadata
12                       sp_followers       streaming
13               sp_monthly_listeners       streaming
14                      sp_popularity       streaming
15                        deezer_fans       streaming
16                       shazam_count       streaming
17           pandora_lifetime_streams       streaming
18    pandora_lifetime_stations_added       streaming
19            sp_playlist_total_reach       playlists
20         num_sp_editorial_playlists       playlists
21                   num_sp_playlists       playlists
22  sp_editorial_playlist_total_reach       playlists
23         num_am_editorial_playlists       playlists
24                   num_am_playlists       playlists
25         num_de_editorial_playlists       playlists
26                   num_de_playlists       playlists
27            de_playlist_total_reach       playlists
28  de_editorial_playlist_total_reach       playlists
29         num_az_editorial_playlists       playlists
30                   num_az_playlists       playlists
31         num_yt_editorial_playlists       playlists
32                   num_yt_playlists       playlists
33            yt_playlist_total_reach       playlists
34                      ins_followers  redes_sociales
35                  twitter_followers  redes_sociales
36                   tiktok_followers  redes_sociales
37                       tiktok_likes  redes_sociales
38             tiktok_top_video_views  redes_sociales
39          tiktok_top_video_comments  redes_sociales
40                 tiktok_track_posts  redes_sociales
41                    ycs_subscribers         youtube
42                          ycs_views         youtube
43          youtube_daily_video_views         youtube
44        youtube_monthly_video_views         youtube
45                      n_shows_24_25     live_events
46        n_shows_with_capacity_24_25     live_events
47                     capacity_24_25     live_events
48           avg_venue_capacity_24_25     live_events
49                     n_cities_24_25     live_events
50                  n_countries_24_25     live_events
51            shows_per_country_24_25     live_events
52                          off_cycle     live_events

# tipos datos

In [56]:
#recupero de la notebook previa

In [8]:
# 1. Definir el diccionario de tipos basado en tu info
dtypes_dict = {
    'chartmetric_id': 'Int64',
    'artist_name': 'str',
    'country': 'category',
    'pronoun_title': 'category',
    'record_label': 'category',
    'primary_genre': 'category',
    'sp_followers': 'Int64',
    'sp_monthly_listeners': 'Int64',
    'sp_popularity': 'float64',
    'sp_playlist_total_reach': 'float64',
    'ins_followers': 'Int64',
    'twitter_followers': 'Int64',
    'tiktok_followers': 'Int64',
    'tiktok_likes': 'Int64',
    'ycs_subscribers': 'Int64',
    'ycs_views': 'Int64',
    'youtube_daily_video_views': 'Int64',
    'youtube_monthly_video_views': 'Int64',
    'deezer_fans': 'Int64',
    'shazam_count': 'Int64',
    'pandora_lifetime_streams': 'Int64',
    'pandora_lifetime_stations_added': 'Int64',
    'band': 'bool',
    'num_sp_editorial_playlists': 'Int64',
    'num_sp_playlists': 'Int64',
    'sp_editorial_playlist_total_reach': 'float64',
    'num_am_editorial_playlists': 'Int64',
    'num_am_playlists': 'Int64',
    'num_de_editorial_playlists': 'Int64',
    'num_de_playlists': 'Int64',
    'de_playlist_total_reach': 'float64',
    'de_editorial_playlist_total_reach': 'float64',
    'num_az_editorial_playlists': 'Int64',
    'num_az_playlists': 'Int64',
    'num_yt_editorial_playlists': 'Int64',
    'num_yt_playlists': 'Int64',
    'yt_playlist_total_reach': 'float64',
    'tiktok_top_video_views': 'float64',
    'tiktok_top_video_comments': 'float64',
    'tiktok_track_posts': 'float64',
    'n_shows_24_25': 'Int64',
    'n_shows_with_capacity_24_25': 'Int64',
    'capacity_24_25': 'float64',
    'avg_venue_capacity_24_25': 'float64',
    'n_cities_24_25': 'Int64',
    'n_countries_24_25': 'Int64',
    'shows_per_country_24_25': 'float64',
    'major_record_label': 'boolean',
    'pronoun_short': 'category',
    'genre_short': 'category',
    'country_short': 'category',
    'off_cycle': 'bool',
    'muerto_disuelto': 'boolean'
}

# 2. Aplicar la conversión al dataframe df
# Código original que podía ocultar conversiones no aplicadas:
# df = df.astype(dtypes_dict, errors='ignore')

# Conversión solo de columnas existentes
dtypes_presentes = {
    col: dtype
    for col, dtype in dtypes_dict.items()
    if col in df.columns
}

df = df.astype(dtypes_presentes)

# 3. Verificación rápida
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 53 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   chartmetric_id                     7000 non-null   Int64
 1   artist_name                        7000 non-null   str
 2   country                            6933 non-null   category
 3   pronoun_title                      7000 non-null   category
 4   record_label                       6476 non-null   category
 5   primary_genre                      7000 non-null   category
 6   sp_followers                       6978 non-null   Int64
 7   sp_monthly_listeners               6978 non-null   Int64
 8   sp_popularity                      6992 non-null   float64
 9   sp_playlist_total_reach            6989 non-null   float64
 10  ins_followers                      6394 non-null   Int64
 11  twitter_followers                  5227 non-null   Int64
 12  tiktok_followers                   4801 non-null   Int64
 13  tiktok_likes                       4801 non-null   Int64
 14  ycs_subscribers                    6381 non-null   Int64
 15  ycs_views                          6381 non-null   Int64
 16  youtube_daily_video_views          4284 non-null   Int64
 17  youtube_monthly_video_views        4284 non-null   Int64
 18  deezer_fans                        6802 non-null   Int64
 19  shazam_count                       6983 non-null   Int64
 20  pandora_lifetime_streams           6530 non-null   Int64
 21  pandora_lifetime_stations_added    6330 non-null   Int64
 22  band                               7000 non-null   bool
 23  num_sp_editorial_playlists         6989 non-null   Int64
 24  num_sp_playlists                   6989 non-null   Int64
 25  sp_editorial_playlist_total_reach  6989 non-null   float64
 26  num_am_editorial_playlists         6774 non-null   Int64
 27  num_am_playlists                   6774 non-null   Int64
 28  num_de_editorial_playlists         6457 non-null   Int64
 29  num_de_playlists                   6457 non-null   Int64
 30  de_playlist_total_reach            6457 non-null   float64
 31  de_editorial_playlist_total_reach  6457 non-null   float64
 32  num_az_editorial_playlists         6201 non-null   Int64
 33  num_az_playlists                   6201 non-null   Int64
 34  num_yt_editorial_playlists         6569 non-null   Int64
 35  num_yt_playlists                   6569 non-null   Int64
 36  yt_playlist_total_reach            6451 non-null   float64
 37  tiktok_top_video_views             6934 non-null   float64
 38  tiktok_top_video_comments          6934 non-null   float64
 39  tiktok_track_posts                 6933 non-null   float64
 40  n_shows_24_25                      4913 non-null   Int64
 41  n_shows_with_capacity_24_25        4913 non-null   Int64
 42  capacity_24_25                     4730 non-null   float64
 43  avg_venue_capacity_24_25           3870 non-null   float64
 44  n_cities_24_25                     4913 non-null   Int64
 45  n_countries_24_25                  4913 non-null   Int64
 46  shows_per_country_24_25            4025 non-null   float64
 47  major_record_label                 6476 non-null   boolean
 48  pronoun_short                      7000 non-null   category
 49  genre_short                        7000 non-null   category
 50  country_short                      6933 non-null   category
 51  muerto_disuelto                    4690 non-null   boolean
 52  off_cycle                          7000 non-null   bool
dtypes: Int64(29), bool(2), boolean(2), category(7), float64(12), str(1)
memory usage: 2.6 MB
None

In [9]:
# Estructura general del dataset
print("Filas y columnas:", df.shape)

# Control de clave única
print("Artistas únicos:", df["chartmetric_id"].nunique())
print("Duplicados por chartmetric_id:", df.duplicated(subset="chartmetric_id").sum())

# Control de target
print("Nulos en target:", df["n_shows_24_25"].isna().sum())
print("Tipo de dato de target:", df["n_shows_24_25"].dtype)

Filas y columnas: (7000, 53)
Artistas únicos: 7000
Duplicados por chartmetric_id: 0
Nulos en target: 2087
Tipo de dato de target: Int64

# multicolinealidad
sin target

In [ ]:
# ============================================================
# Pares de variables digitales altamente correlacionadas
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Parámetros
# ------------------------------------------------------------

umbral_corr = 0.70

df_multi = df.copy()

# ------------------------------------------------------------
# Variables digitales candidatas
# Se usan solo variables digitales numéricas efectivamente presentes en el dataframe
# ------------------------------------------------------------

digital_cols = (
    streaming_cols
    + playlist_cols
    + social_cols
    + youtube_cols
)

digital_numeric_vars = [
    col for col in digital_cols
    if col in df_multi.columns and pd.api.types.is_numeric_dtype(df_multi[col])
]

print("Variables digitales candidatas:", len(digital_cols))
print("Variables digitales numéricas disponibles:", len(digital_numeric_vars))

# ------------------------------------------------------------
# Transformación log1p para variables digitales no acotadas
# sp_popularity se conserva en escala original por estar acotada entre 0 y 100
# ------------------------------------------------------------

vars_log = [
    col for col in digital_numeric_vars
    if col != "sp_popularity"
]

for col in vars_log:
    df_multi[f"log1p_{col}"] = np.log1p(df_multi[col].astype(float))

vars_multi = [f"log1p_{col}" for col in vars_log]

if "sp_popularity" in digital_numeric_vars:
    vars_multi = vars_multi + ["sp_popularity"]

# ------------------------------------------------------------
# Matriz de correlación entre variables digitales
# ------------------------------------------------------------

corr_matrix = df_multi[vars_multi].corr(method="pearson")

corr_pairs = (
    corr_matrix
    .where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    .stack()
    .reset_index()
)

corr_pairs.columns = ["variable_1", "variable_2", "correlacion_entre_vars"]

corr_pairs["abs_correlacion_entre_vars"] = corr_pairs["correlacion_entre_vars"].abs()

corr_pairs_altas = (
    corr_pairs
    .loc[corr_pairs["abs_correlacion_entre_vars"] >= umbral_corr]
    .sort_values("abs_correlacion_entre_vars", ascending=False)
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# Funciones auxiliares para recuperar variable original y dimensión
# ------------------------------------------------------------

def quitar_log1p(variable):
    return variable.replace("log1p_", "")

def asignar_dimension(variable):
    if variable in streaming_cols:
        return "streaming"
    elif variable in playlist_cols:
        return "playlists"
    elif variable in social_cols:
        return "redes_sociales"
    elif variable in youtube_cols:
        return "youtube"
    else:
        return "otra"

corr_pairs_altas["var1_original"] = corr_pairs_altas["variable_1"].apply(quitar_log1p)
corr_pairs_altas["var2_original"] = corr_pairs_altas["variable_2"].apply(quitar_log1p)

corr_pairs_altas["dimension_1"] = corr_pairs_altas["var1_original"].apply(asignar_dimension)
corr_pairs_altas["dimension_2"] = corr_pairs_altas["var2_original"].apply(asignar_dimension)

# ------------------------------------------------------------
# Porcentaje de nulos por variable
# ------------------------------------------------------------

null_pct_lookup = (
    df_multi[digital_numeric_vars]
    .isna()
    .mean()
    .mul(100)
    .round(2)
    .to_dict()
)

corr_pairs_altas["pct_null_var1"] = corr_pairs_altas["var1_original"].map(null_pct_lookup)
corr_pairs_altas["pct_null_var2"] = corr_pairs_altas["var2_original"].map(null_pct_lookup)

# ------------------------------------------------------------
# Selección de columnas para revisión
# ------------------------------------------------------------

corr_pairs_altas = corr_pairs_altas[
    [
        "var1_original",
        "var2_original",
        "dimension_1",
        "dimension_2",
        "correlacion_entre_vars",
        "abs_correlacion_entre_vars",
        "pct_null_var1",
        "pct_null_var2"
    ]
].round({
    "correlacion_entre_vars": 3,
    "abs_correlacion_entre_vars": 3,
    "pct_null_var1": 2,
    "pct_null_var2": 2
})

pd.set_option("display.max_rows", 150)
pd.set_option("display.min_rows", 150)

corr_pairs_altas

Variables digitales candidatas: 33
Variables digitales numéricas disponibles: 33

,var1_original,var2_original,dimension_1,dimension_2,correlacion_entre_vars,abs_correlacion_entre_vars,pct_null_var1,pct_null_var2
0,num_az_editorial_playlists,num_az_playlists,playlists,playlists,0.996,0.996,11.41,11.41
1,tiktok_top_video_views,tiktok_top_video_comments,redes_sociales,redes_sociales,0.975,0.975,0.94,0.94
2,num_am_editorial_playlists,num_am_playlists,playlists,playlists,0.949,0.949,3.23,3.23
3,sp_monthly_listeners,sp_popularity,streaming,streaming,0.935,0.935,0.31,0.11
4,pandora_lifetime_streams,pandora_lifetime_stations_added,streaming,streaming,0.934,0.934,6.71,9.57
5,tiktok_followers,tiktok_likes,redes_sociales,redes_sociales,0.927,0.927,31.41,31.41
6,tiktok_top_video_views,tiktok_track_posts,redes_sociales,redes_sociales,0.925,0.925,0.94,0.96
7,tiktok_top_video_comments,tiktok_track_posts,redes_sociales,redes_sociales,0.922,0.922,0.94,0.96
8,sp_playlist_total_reach,num_sp_playlists,playlists,playlists,0.920,0.920,0.16,0.16
9,shazam_count,num_sp_playlists,streaming,playlists,0.888,0.888,0.24,0.16
10,ycs_subscribers,ycs_views,youtube,youtube,0.878,0.878,8.84,8.84
11,num_de_editorial_playlists,num_de_playlists,playlists,playlists,0.877,0.877,7.76,7.76
12,num_sp_editorial_playlists,num_am_playlists,playlists,playlists,0.857,0.857,0.16,3.23
13,sp_monthly_listeners,sp_playlist_total_reach,streaming,playlists,0.855,0.855,0.31,0.16
14,sp_playlist_total_reach,sp_editorial_playlist_total_reach,playlists,playlists,0.841,0.841,0.16,0.16
15,num_sp_editorial_playlists,num_am_editorial_playlists,playlists,playlists,0.837,0.837,0.16,3.23
16,sp_playlist_total_reach,num_sp_editorial_playlists,playlists,playlists,0.830,0.830,0.16,0.16
17,shazam_count,sp_playlist_total_reach,streaming,playlists,0.829,0.829,0.24,0.16
18,sp_playlist_total_reach,sp_popularity,playlists,streaming,0.829,0.829,0.16,0.11
19,de_playlist_total_reach,de_editorial_playlist_total_reach,playlists,playlists,0.827,0.827,7.76,7.76
20,num_sp_editorial_playlists,num_sp_playlists,playlists,playlists,0.822,0.822,0.16,0.16
21,num_de_playlists,de_playlist_total_reach,playlists,playlists,0.816,0.816,7.76,7.76
22,num_sp_playlists,num_am_playlists,playlists,playlists,0.810,0.810,0.16,3.23
23,num_de_editorial_playlists,de_playlist_total_reach,playlists,playlists,0.801,0.801,7.76,7.76
24,num_de_editorial_playlists,de_editorial_playlist_total_reach,playlists,playlists,0.798,0.798,7.76,7.76
25,num_am_playlists,num_de_playlists,playlists,playlists,0.796,0.796,3.23,7.76
26,sp_monthly_listeners,num_sp_playlists,streaming,playlists,0.793,0.793,0.31,0.16
27,num_am_editorial_playlists,num_az_playlists,playlists,playlists,0.790,0.790,3.23,11.41
28,num_sp_playlists,sp_popularity,playlists,streaming,0.788,0.788,0.16,0.11
29,shazam_count,num_sp_editorial_playlists,streaming,playlists,0.785,0.785,0.24,0.16
30,num_am_editorial_playlists,num_az_editorial_playlists,playlists,playlists,0.784,0.784,3.23,11.41
31,num_am_playlists,num_az_playlists,playlists,playlists,0.783,0.783,3.23,11.41
32,sp_playlist_total_reach,num_am_playlists,playlists,playlists,0.782,0.782,0.16,3.23
33,num_yt_editorial_playlists,num_yt_playlists,playlists,playlists,0.781,0.781,6.16,6.16
34,sp_monthly_listeners,sp_editorial_playlist_total_reach,streaming,playlists,0.779,0.779,0.31,0.16
35,youtube_daily_video_views,youtube_monthly_video_views,youtube,youtube,0.774,0.774,38.80,38.80
36,num_am_playlists,num_az_editorial_playlists,playlists,playlists,0.774,0.774,3.23,11.41
37,shazam_count,num_am_playlists,streaming,playlists,0.773,0.773,0.24,3.23
38,sp_editorial_playlist_total_reach,sp_popularity,playlists,streaming,0.770,0.770,0.16,0.11
39,num_sp_editorial_playlists,sp_editorial_playlist_total_reach,playlists,playlists,0.763,0.763,0.16,0.16
40,sp_followers,sp_popularity,streaming,streaming,0.760,0.760,0.31,0.11
41,sp_monthly_listeners,shazam_count,streaming,streaming,0.755,0.755,0.31,0.24
42,num_am_playlists,num_de_editorial_playlists,playlists,playlists,0.754,0.754,3.23,7.76
43,shazam_count,sp_popularity,streaming,streaming,0.750,0.750,0.24,0.11
44,num_sp_playlists,sp_editorial_playlist_total_reach,playlists,playlists,0.745,0.745,0.16,0.16
45,num_sp_editorial_playlists,num_az_playlists,playlists,playlists,0.744,0.744,0.16,11.41
46,sp_playlist_total_reach,num_yt_playlists,playlists,playlists,0.740,0.740,0.16,6.16
47,num_sp_editorial_playlists,num_de_playlists,playlists,playlists,0.739,0.739,0.16,7.76
48,num_sp_editorial_playlists,num_az_editorial_playlists,playlists,playlists,0.738,0.738,0.16,11.41
49,num_yt_playlists,yt_playlist_total_reach,playlists,playlists,0.735,0.735,6.16,7.84
50,num_am_playlists,num_yt_playlists,playlists,playlists,0.732,0.732,3.23,6.16
51,num_sp_playlists,num_am_editorial_playlists,playlists,playlists,0.732,0.732,0.16,3.23
52,sp_playlist_total_reach,num_de_playlists,playlists,playlists,0.729,0.729,0.16,7.76
53,sp_playlist_total_reach,num_az_playlists,playlists,playlists,0.727,0.727,0.16,11.41
54,num_sp_playlists,num_de_playlists,playlists,playlists,0.721,0.721,0.16,7.76
55,shazam_count,num_am_editorial_playlists,streaming,playlists,0.721,0.721,0.24,3.23
56,sp_followers,sp_monthly_listeners,streaming,streaming,0.720,0.720,0.31,0.31
57,num_sp_editorial_playlists,sp_popularity,playlists,streaming,0.718,0.718,0.16,0.11
58,sp_playlist_total_reach,num_az_editorial_playlists,playlists,playlists,0.718,0.718,0.16,11.41
59,sp_playlist_total_reach,num_am_editorial_playlists,playlists,playlists,0.716,0.716,0.16,3.23
60,num_sp_editorial_playlists,num_yt_playlists,playlists,playlists,0.714,0.714,0.16,6.16
61,num_de_playlists,de_editorial_playlist_total_reach,playlists,playlists,0.706,0.706,7.76,7.76
62,num_am_editorial_playlists,num_de_playlists,playlists,playlists,0.704,0.704,3.23,7.76
63,num_am_editorial_playlists,num_yt_editorial_playlists,playlists,playlists,0.702,0.702,3.23,6.16
64,num_sp_playlists,num_yt_playlists,playlists,playlists,0.701,0.701,0.16,6.16
65,num_am_playlists,num_yt_editorial_playlists,playlists,playlists,0.701,0.701,3.23,6.16
66,num_am_editorial_playlists,num_de_editorial_playlists,playlists,playlists,0.701,0.701,3.23,7.76
67,num_sp_editorial_playlists,num_yt_editorial_playlists,playlists,playlists,0.701,0.701,0.16,6.16
68,num_sp_editorial_playlists,num_de_editorial_playlists,playlists,playlists,0.700,0.700,0.16,7.76

In [12]:
# ============================================================
# Variables más involucradas en pares altamente correlacionados
# ============================================================

# ------------------------------------------------------------
# Tabla larga con una fila por variable dentro de cada par
# ------------------------------------------------------------

vars_en_pares_1 = corr_pairs_altas[
    [
        "var1_original",
        "dimension_1",
        "abs_correlacion_entre_vars",
        "pct_null_var1"
    ]
].copy()

vars_en_pares_1.columns = [
    "variable",
    "dimension",
    "abs_correlacion_entre_vars",
    "pct_null"
]

vars_en_pares_2 = corr_pairs_altas[
    [
        "var2_original",
        "dimension_2",
        "abs_correlacion_entre_vars",
        "pct_null_var2"
    ]
].copy()

vars_en_pares_2.columns = [
    "variable",
    "dimension",
    "abs_correlacion_entre_vars",
    "pct_null"
]

vars_en_pares = pd.concat(
    [vars_en_pares_1, vars_en_pares_2],
    ignore_index=True
)

# ------------------------------------------------------------
# Resumen por variable
# ------------------------------------------------------------

redundancia_por_variable = (
    vars_en_pares
    .groupby(["variable", "dimension"])
    .agg(
        n_pares_altos=("abs_correlacion_entre_vars", "count"),
        max_corr_con_otra_var=("abs_correlacion_entre_vars", "max"),
        corr_media_con_otras_vars=("abs_correlacion_entre_vars", "mean"),
        pct_null=("pct_null", "first")
    )
    .reset_index()
)

redundancia_por_variable = (
    redundancia_por_variable
    .sort_values(
        ["n_pares_altos", "max_corr_con_otra_var", "pct_null"],
        ascending=[False, False, True]
    )
    .reset_index(drop=True)
)

redundancia_por_variable = redundancia_por_variable.round({
    "max_corr_con_otra_var": 3,
    "corr_media_con_otras_vars": 3,
    "pct_null": 2
})

redundancia_por_variable

,variable,dimension,n_pares_altos,max_corr_con_otra_var,corr_media_con_otras_vars,pct_null
0,num_sp_editorial_playlists,playlists,13,0.857,0.765,0.16
1,sp_playlist_total_reach,playlists,12,0.920,0.793,0.16
2,num_am_playlists,playlists,11,0.949,0.792,3.23
3,num_am_editorial_playlists,playlists,10,0.949,0.764,3.23
4,num_sp_playlists,playlists,10,0.920,0.792,0.16
5,num_de_playlists,playlists,8,0.877,0.761,7.76
6,sp_popularity,streaming,7,0.935,0.793,0.11
7,shazam_count,streaming,7,0.888,0.786,0.24
8,sp_monthly_listeners,streaming,6,0.935,0.806,0.31
9,num_de_editorial_playlists,playlists,6,0.877,0.772,7.76
10,num_yt_playlists,playlists,6,0.781,0.734,6.16
11,num_az_editorial_playlists,playlists,5,0.996,0.802,11.41
12,num_az_playlists,playlists,5,0.996,0.808,11.41
13,sp_editorial_playlist_total_reach,playlists,5,0.841,0.780,0.16
14,num_yt_editorial_playlists,playlists,4,0.781,0.721,6.16
15,de_editorial_playlist_total_reach,playlists,3,0.827,0.777,7.76
16,de_playlist_total_reach,playlists,3,0.827,0.815,7.76
17,tiktok_top_video_comments,redes_sociales,2,0.975,0.948,0.94
18,tiktok_top_video_views,redes_sociales,2,0.975,0.950,0.94
19,tiktok_track_posts,redes_sociales,2,0.925,0.924,0.96
20,sp_followers,streaming,2,0.760,0.740,0.31
21,pandora_lifetime_streams,streaming,1,0.934,0.934,6.71
22,pandora_lifetime_stations_added,streaming,1,0.934,0.934,9.57
23,tiktok_followers,redes_sociales,1,0.927,0.927,31.41
24,tiktok_likes,redes_sociales,1,0.927,0.927,31.41
25,ycs_subscribers,youtube,1,0.878,0.878,8.84
26,ycs_views,youtube,1,0.878,0.878,8.84
27,youtube_daily_video_views,youtube,1,0.774,0.774,38.80
28,youtube_monthly_video_views,youtube,1,0.774,0.774,38.80
29,yt_playlist_total_reach,playlists,1,0.735,0.735,7.84

In [17]:
# ============================================================
# Exportación de tablas de redundancia para revisión
# ============================================================

archivo_redundancia_clustering = "salidas_redundancia_clustering.xlsx"

with pd.ExcelWriter(archivo_redundancia_clustering) as writer:
    corr_pairs_altas.to_excel(
        writer,
        sheet_name="pares_correlacionados",
        index=False
    )
    
    redundancia_por_variable.to_excel(
        writer,
        sheet_name="redundancia_variable",
        index=False
    )

archivo_redundancia_clustering

'salidas_redundancia_clustering.xlsx'

# nulos e imput para lineal

In [ ]:
# # ------------------------------------------------------------
# # Diagnóstico de nulos antes de ajustar regresión lineal
# # ------------------------------------------------------------

# resumen_nulos_modelo = (
#     df_modelo_lineal
#     .isna()
#     .sum()
#     .reset_index()
# )

# resumen_nulos_modelo.columns = ["variable", "n_null"]

# resumen_nulos_modelo["pct_null"] = (
#     resumen_nulos_modelo["n_null"] / len(df_modelo_lineal) * 100
# ).round(2)

# resumen_nulos_modelo = (
#     resumen_nulos_modelo
#     .sort_values("pct_null", ascending=False)
#     .reset_index(drop=True)
# )

# display(resumen_nulos_modelo)

# # ------------------------------------------------------------
# # Registros completos por bloque
# # ------------------------------------------------------------

# columnas_numericas_modelo = [
#     "log1p_n_shows_24_25"
# ] + variables_regresion_final_log

# columnas_categoricas_modelo = categoricas_regresion.copy()

# n_total = df_modelo_lineal.shape[0]

# n_completo_numericas = (
#     df_modelo_lineal[columnas_numericas_modelo]
#     .dropna()
#     .shape[0]
# )

# n_completo_categoricas = (
#     df_modelo_lineal[columnas_categoricas_modelo]
#     .dropna()
#     .shape[0]
# )

# n_completo_total = df_modelo_lineal.dropna().shape[0]

# print("Artistas iniciales:", n_total)

# print(
#     "Artistas completos en variables numéricas:",
#     n_completo_numericas,
#     "| porcentaje:",
#     round(n_completo_numericas / n_total * 100, 2)
# )

# print(
#     "Artistas completos en variables categóricas:",
#     n_completo_categoricas,
#     "| porcentaje:",
#     round(n_completo_categoricas / n_total * 100, 2)
# )

# print(
#     "Artistas completos en todo el set de modelado:",
#     n_completo_total,
#     "| porcentaje:",
#     round(n_completo_total / n_total * 100, 2)
# )

# print(
#     "Artistas que se perderían si se aplica dropna total:",
#     n_total - n_completo_total
# )

                            variable  n_null  pct_null
0            log1p_twitter_followers     945     19.23
1                log1p_ins_followers     333      6.78
2                 major_record_label     309      6.29
3                    log1p_ycs_views     243      4.95
4     log1p_pandora_lifetime_streams      96      1.95
5   log1p_num_yt_editorial_playlists      94      1.91
6                  log1p_deezer_fans      60      1.22
7    log1p_tiktok_top_video_comments       8      0.16
8         log1p_sp_monthly_listeners       6      0.12
9                      country_short       4      0.08
10            log1p_num_sp_playlists       0      0.00
11                    chartmetric_id       0      0.00
12               log1p_n_shows_24_25       0      0.00
13                       genre_short       0      0.00
14                     pronoun_short       0      0.00
15                              band       0      0.00

Artistas iniciales: 4913
Artistas completos en variables numéricas: 3684 | porcentaje: 74.98
Artistas completos en variables categóricas: 4600 | porcentaje: 93.63
Artistas completos en todo el set de modelado: 3487 | porcentaje: 70.97
Artistas que se perderían si se aplica dropna total: 1426

In [ ]:
# # ------------------------------------------------------------
# # Tratamiento de nulos para regresión lineal
# # ------------------------------------------------------------

# df_modelo_lineal_imp = df_modelo_lineal.copy()

# # ------------------------------------------------------------
# # Variables imputadas con valor sustantivo
# # ------------------------------------------------------------

# df_modelo_lineal_imp["log1p_twitter_followers_imp"] = (
#     df_modelo_lineal_imp["log1p_twitter_followers"]
#     .fillna(0)
# )

# df_modelo_lineal_imp["log1p_ins_followers_imp"] = (
#     df_modelo_lineal_imp["log1p_ins_followers"]
#     .fillna(0)
# )

# df_modelo_lineal_imp["major_record_label_imp"] = (
#     df_modelo_lineal_imp["major_record_label"]
#     .fillna(False)
# )

# # ------------------------------------------------------------
# # Variables copiadas con sufijo _imp para conservar trazabilidad
# # ------------------------------------------------------------

# df_modelo_lineal_imp["log1p_ycs_views_imp"] = df_modelo_lineal_imp["log1p_ycs_views"]
# df_modelo_lineal_imp["log1p_pandora_lifetime_streams_imp"] = df_modelo_lineal_imp["log1p_pandora_lifetime_streams"]
# df_modelo_lineal_imp["log1p_num_yt_editorial_playlists_imp"] = df_modelo_lineal_imp["log1p_num_yt_editorial_playlists"]
# df_modelo_lineal_imp["log1p_deezer_fans_imp"] = df_modelo_lineal_imp["log1p_deezer_fans"]
# df_modelo_lineal_imp["log1p_tiktok_top_video_comments_imp"] = df_modelo_lineal_imp["log1p_tiktok_top_video_comments"]
# df_modelo_lineal_imp["log1p_sp_monthly_listeners_imp"] = df_modelo_lineal_imp["log1p_sp_monthly_listeners"]
# df_modelo_lineal_imp["country_short_imp"] = df_modelo_lineal_imp["country_short"]

# # ------------------------------------------------------------
# # Drop de registros con nulos remanentes
# # ------------------------------------------------------------

# variables_dropna_imp = [
#     "log1p_ycs_views_imp",
#     "log1p_pandora_lifetime_streams_imp",
#     "log1p_num_yt_editorial_playlists_imp",
#     "log1p_deezer_fans_imp",
#     "log1p_tiktok_top_video_comments_imp",
#     "log1p_sp_monthly_listeners_imp",
#     "country_short_imp"
# ]

# n_antes = df_modelo_lineal_imp.shape[0]

# df_modelo_lineal_imp = (
#     df_modelo_lineal_imp
#     .dropna(subset=variables_dropna_imp)
#     .copy()
# )

# n_despues = df_modelo_lineal_imp.shape[0]

# print("Artistas antes del tratamiento:", n_antes)
# print("Artistas después del tratamiento:", n_despues)
# print("Artistas eliminados por nulos remanentes:", n_antes - n_despues)
# print("Porcentaje conservado:", round(n_despues / n_antes * 100, 2))

# # ------------------------------------------------------------
# # Listas finales para modelado
# # ------------------------------------------------------------

# features_numericas_imp = [
#     "log1p_num_yt_editorial_playlists_imp",
#     "log1p_num_sp_playlists",
#     "log1p_ins_followers_imp",
#     "log1p_twitter_followers_imp",
#     "log1p_tiktok_top_video_comments_imp",
#     "log1p_sp_monthly_listeners_imp",
#     "log1p_pandora_lifetime_streams_imp",
#     "log1p_deezer_fans_imp",
#     "log1p_ycs_views_imp"
# ]

# features_categoricas_imp = [
#     "country_short_imp",
#     "genre_short",
#     "pronoun_short",
#     "band",
#     "major_record_label_imp"
# ]

# features_modelo_imp = features_numericas_imp + features_categoricas_imp

# # ------------------------------------------------------------
# # Control final de nulos
# # ------------------------------------------------------------

# resumen_nulos_imp = (
#     df_modelo_lineal_imp[
#         ["log1p_n_shows_24_25"] + features_modelo_imp
#     ]
#     .isna()
#     .sum()
#     .reset_index()
# )

# resumen_nulos_imp.columns = ["variable", "n_null"]

# resumen_nulos_imp["pct_null"] = (
#     resumen_nulos_imp["n_null"] / len(df_modelo_lineal_imp) * 100
# ).round(2)

# display(resumen_nulos_imp)

Artistas antes del tratamiento: 4913
Artistas después del tratamiento: 4505
Artistas eliminados por nulos remanentes: 408
Porcentaje conservado: 91.7

                                variable  n_null  pct_null
0                    log1p_n_shows_24_25       0       0.0
1   log1p_num_yt_editorial_playlists_imp       0       0.0
2                 log1p_num_sp_playlists       0       0.0
3                log1p_ins_followers_imp       0       0.0
4            log1p_twitter_followers_imp       0       0.0
5    log1p_tiktok_top_video_comments_imp       0       0.0
6         log1p_sp_monthly_listeners_imp       0       0.0
7     log1p_pandora_lifetime_streams_imp       0       0.0
8                  log1p_deezer_fans_imp       0       0.0
9                    log1p_ycs_views_imp       0       0.0
10                     country_short_imp       0       0.0
11                           genre_short       0       0.0
12                         pronoun_short       0       0.0
13                                  band       0       0.0
14                major_record_label_imp       0       0.0

# selección variables

In [18]:
# ============================================================
# Selección de variables digitales para clustering
# Criterio: representación de dimensiones y reducción de redundancia
# ============================================================

variables_clustering_digitales_base = [
    # Streaming
    "sp_monthly_listeners",
    "sp_followers",
    "deezer_fans",
    "pandora_lifetime_streams",

    # Playlists
    "num_sp_playlists",
    "num_am_playlists",
    "num_yt_editorial_playlists",

    # Redes sociales
    "ins_followers",
    "twitter_followers",
    "tiktok_followers",
    "tiktok_top_video_comments",

    # YouTube
    "ycs_views"
]

variables_clustering_digitales_base = [
    col for col in variables_clustering_digitales_base
    if col in df.columns
]

len(variables_clustering_digitales_base), variables_clustering_digitales_base

(12,
 ['sp_monthly_listeners',
  'sp_followers',
  'deezer_fans',
  'pandora_lifetime_streams',
  'num_sp_playlists',
  'num_am_playlists',
  'num_yt_editorial_playlists',
  'ins_followers',
  'twitter_followers',
  'tiktok_followers',
  'tiktok_top_video_comments',
  'ycs_views'])

# nulos

In [19]:
# ============================================================
# Diagnóstico de valores faltantes en variables de clustering
# ============================================================

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# Variables activas seleccionadas para clustering
# ------------------------------------------------------------

variables_clustering_digitales_base = [
    # Streaming
    "sp_monthly_listeners",
    "sp_followers",
    "deezer_fans",
    "pandora_lifetime_streams",

    # Playlists
    "num_sp_playlists",
    "num_am_playlists",
    "num_yt_editorial_playlists",

    # Redes sociales
    "ins_followers",
    "twitter_followers",
    "tiktok_followers",
    "tiktok_top_video_comments",

    # YouTube
    "ycs_views"
]

variables_clustering_digitales_base = [
    col for col in variables_clustering_digitales_base
    if col in df.columns
]

# ------------------------------------------------------------
# Tabla de nulos por variable
# ------------------------------------------------------------

tabla_nulos_clustering = (
    df[variables_clustering_digitales_base]
    .isna()
    .agg(["sum", "mean"])
    .T
    .reset_index()
)

tabla_nulos_clustering.columns = [
    "variable",
    "n_nulos",
    "pct_nulos"
]

tabla_nulos_clustering["pct_nulos"] = (
    tabla_nulos_clustering["pct_nulos"] * 100
).round(2)

tabla_nulos_clustering = (
    tabla_nulos_clustering
    .sort_values("pct_nulos", ascending=False)
    .reset_index(drop=True)
)

tabla_nulos_clustering

                      variable  n_nulos  pct_nulos
0             tiktok_followers   2199.0      31.41
1            twitter_followers   1773.0      25.33
2                    ycs_views    619.0       8.84
3                ins_followers    606.0       8.66
4     pandora_lifetime_streams    470.0       6.71
5   num_yt_editorial_playlists    431.0       6.16
6             num_am_playlists    226.0       3.23
7                  deezer_fans    198.0       2.83
8    tiktok_top_video_comments     66.0       0.94
9                 sp_followers     22.0       0.31
10        sp_monthly_listeners     22.0       0.31
11            num_sp_playlists     11.0       0.16

In [20]:
# ============================================================
# Cobertura de casos completos en matriz de clustering
# ============================================================

n_total_artistas = len(df)

n_artistas_completos = (
    df[variables_clustering_digitales_base]
    .notna()
    .all(axis=1)
    .sum()
)

pct_artistas_completos = round(
    n_artistas_completos / n_total_artistas * 100,
    2
)

resumen_cobertura_clustering = pd.DataFrame({
    "indicador": [
        "artistas_totales",
        "artistas_sin_nulos_en_variables_clustering",
        "porcentaje_sin_nulos"
    ],
    "valor": [
        n_total_artistas,
        n_artistas_completos,
        pct_artistas_completos
    ]
})

resumen_cobertura_clustering

                                    indicador    valor
0                            artistas_totales  7000.00
1  artistas_sin_nulos_en_variables_clustering  3651.00
2                        porcentaje_sin_nulos    52.16

In [21]:
# ============================================================
# Cantidad de variables faltantes por artista
# ============================================================

nulos_por_artista_clustering = (
    df[variables_clustering_digitales_base]
    .isna()
    .sum(axis=1)
)

distribucion_nulos_por_artista = (
    nulos_por_artista_clustering
    .value_counts()
    .sort_index()
    .reset_index()
)

distribucion_nulos_por_artista.columns = [
    "n_variables_faltantes",
    "n_artistas"
]

distribucion_nulos_por_artista["pct_artistas"] = (
    distribucion_nulos_por_artista["n_artistas"] / len(df) * 100
).round(2)

distribucion_nulos_por_artista

    n_variables_faltantes  n_artistas  pct_artistas
0                       0        3651         52.16
1                       1        1741         24.87
2                       2         764         10.91
3                       3         416          5.94
4                       4         227          3.24
5                       5         100          1.43
6                       6          42          0.60
7                       7          28          0.40
8                       8          16          0.23
9                       9          10          0.14
10                     10           4          0.06
11                     12           1          0.01

# imputación 
0 y flags

In [22]:
# ============================================================
# Tratamiento de nulos para matriz de clustering digital
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Variables activas seleccionadas para clustering
# ------------------------------------------------------------

variables_clustering_digitales_base = [
    # Streaming
    "sp_monthly_listeners",
    "sp_followers",
    "deezer_fans",
    "pandora_lifetime_streams",

    # Playlists
    "num_sp_playlists",
    "num_am_playlists",
    "num_yt_editorial_playlists",

    # Redes sociales
    "ins_followers",
    "twitter_followers",
    "tiktok_followers",
    "tiktok_top_video_comments",

    # YouTube
    "ycs_views"
]

variables_clustering_digitales_base = [
    col for col in variables_clustering_digitales_base
    if col in df.columns
]

df_clustering = df.copy()

# ------------------------------------------------------------
# Variables con faltantes relevantes
# Los indicadores conservan información sobre ausencia de dato original
# ------------------------------------------------------------

variables_con_flag_missing = [
    "tiktok_followers",
    "twitter_followers",
    "ins_followers",
    "ycs_views"
]

variables_con_flag_missing = [
    col for col in variables_con_flag_missing
    if col in variables_clustering_digitales_base
]

for col in variables_con_flag_missing:
    df_clustering[f"missing_{col}"] = df_clustering[col].isna().astype(int)

# ------------------------------------------------------------
# Imputación con 0 en variables digitales seleccionadas
# ------------------------------------------------------------

df_clustering[variables_clustering_digitales_base] = (
    df_clustering[variables_clustering_digitales_base]
    .fillna(0)
)

# ------------------------------------------------------------
# Control posterior de nulos
# ------------------------------------------------------------

control_nulos_post_imputacion = (
    df_clustering[variables_clustering_digitales_base]
    .isna()
    .sum()
    .reset_index()
)

control_nulos_post_imputacion.columns = [
    "variable",
    "n_nulos_post_imputacion"
]

control_nulos_post_imputacion

                      variable  n_nulos_post_imputacion
0         sp_monthly_listeners                        0
1                 sp_followers                        0
2                  deezer_fans                        0
3     pandora_lifetime_streams                        0
4             num_sp_playlists                        0
5             num_am_playlists                        0
6   num_yt_editorial_playlists                        0
7                ins_followers                        0
8            twitter_followers                        0
9             tiktok_followers                        0
10   tiktok_top_video_comments                        0
11                   ycs_views                        0

In [23]:
# ============================================================
# Variables activas finales para clustering
# Incluyen variables digitales imputadas e indicadores de faltante
# ============================================================

missing_cols_clustering = [
    f"missing_{col}"
    for col in variables_con_flag_missing
]

variables_clustering_activas = (
    variables_clustering_digitales_base
    + missing_cols_clustering
)

variables_clustering_activas

['sp_monthly_listeners',
 'sp_followers',
 'deezer_fans',
 'pandora_lifetime_streams',
 'num_sp_playlists',
 'num_am_playlists',
 'num_yt_editorial_playlists',
 'ins_followers',
 'twitter_followers',
 'tiktok_followers',
 'tiktok_top_video_comments',
 'ycs_views',
 'missing_tiktok_followers',
 'missing_twitter_followers',
 'missing_ins_followers',
 'missing_ycs_views']

In [24]:
len(variables_clustering_activas), variables_clustering_activas

(16,
 ['sp_monthly_listeners',
  'sp_followers',
  'deezer_fans',
  'pandora_lifetime_streams',
  'num_sp_playlists',
  'num_am_playlists',
  'num_yt_editorial_playlists',
  'ins_followers',
  'twitter_followers',
  'tiktok_followers',
  'tiktok_top_video_comments',
  'ycs_views',
  'missing_tiktok_followers',
  'missing_twitter_followers',
  'missing_ins_followers',
  'missing_ycs_views'])

# transformación y escalado

In [27]:
# ============================================================
# Transformación log1p y matriz de clustering con flags binarios
# ============================================================

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

# ------------------------------------------------------------
# Transformación log1p de variables digitales imputadas
# ------------------------------------------------------------

variables_log_clustering = []

for col in variables_clustering_digitales_base:
    col_log = f"log1p_{col}"
    df_clustering[col_log] = np.log1p(df_clustering[col].astype(float))
    variables_log_clustering.append(col_log)

# ------------------------------------------------------------
# Escalado solo de variables digitales transformadas
# ------------------------------------------------------------

scaler_clustering = StandardScaler()

X_metricas_escaladas = pd.DataFrame(
    scaler_clustering.fit_transform(df_clustering[variables_log_clustering]),
    columns=variables_log_clustering,
    index=df_clustering.index
)

# ------------------------------------------------------------
# Flags de faltante conservados como variables binarias 0/1
# ------------------------------------------------------------

X_flags_missing = df_clustering[missing_cols_clustering].astype(int).copy()

# ------------------------------------------------------------
# Matriz final de clustering
# ------------------------------------------------------------

X_clustering = pd.concat(
    [
        X_metricas_escaladas,
        X_flags_missing
    ],
    axis=1
)

# ------------------------------------------------------------
# Controles finales
# ------------------------------------------------------------

print("Filas en X_clustering:", X_clustering.shape[0])
print("Columnas en X_clustering:", X_clustering.shape[1])
print("Nulos en X_clustering:", X_clustering.isna().sum().sum())

display(X_clustering.head())

Filas en X_clustering: 7000
Columnas en X_clustering: 16
Nulos en X_clustering: 0

,log1p_sp_monthly_listeners,log1p_sp_followers,log1p_deezer_fans,log1p_pandora_lifetime_streams,log1p_num_sp_playlists,log1p_num_am_playlists,log1p_num_yt_editorial_playlists,log1p_ins_followers,log1p_twitter_followers,log1p_tiktok_followers,log1p_tiktok_top_video_comments,log1p_ycs_views,missing_tiktok_followers,missing_twitter_followers,missing_ins_followers,missing_ycs_views
0,1.914626,2.514643,-0.298193,1.195927,1.838432,2.113402,2.842698,1.348771,1.295931,1.413118,2.025840,1.144065,0,0,0,0
1,1.868299,2.667465,1.979320,1.351039,1.877801,2.299534,3.168892,1.732188,1.801204,1.378120,2.101130,1.136214,0,0,0,0
2,2.001417,2.348502,1.980148,1.321781,2.082042,2.292813,2.915932,1.291796,1.659839,1.260004,1.866343,1.044235,0,0,0,0
3,1.848262,2.391366,1.948468,1.231750,2.109801,2.596144,2.927569,1.741542,1.824475,1.358336,2.047585,1.109241,0,0,0,0
4,1.923727,2.545559,2.014308,1.337527,2.218482,2.559407,2.829881,1.428964,1.513341,1.200112,1.714604,1.101479,0,0,0,0

In [28]:
# ============================================================
# Control descriptivo de matriz escalada
# ============================================================

control_matriz_clustering = (
    X_clustering
    .agg(["mean", "std", "min", "max"])
    .T
    .round(3)
)

display(control_matriz_clustering)

                                   mean    std    min    max
log1p_sp_monthly_listeners        0.000  1.000 -7.331  2.001
log1p_sp_followers               -0.000  1.000 -6.613  2.736
log1p_deezer_fans                 0.000  1.000 -2.049  2.105
log1p_pandora_lifetime_streams   -0.000  1.000 -2.558  1.510
log1p_num_sp_playlists            0.000  1.000 -6.901  2.233
log1p_num_am_playlists           -0.000  1.000 -2.824  2.792
log1p_num_yt_editorial_playlists  0.000  1.000 -1.521  3.186
log1p_ins_followers               0.000  1.000 -2.831  1.824
log1p_twitter_followers          -0.000  1.000 -1.535  1.838
log1p_tiktok_followers            0.000  1.000 -1.391  1.541
log1p_tiktok_top_video_comments  -0.000  1.000 -5.124  2.496
log1p_ycs_views                   0.000  1.000 -2.826  1.394
missing_tiktok_followers          0.314  0.464  0.000  1.000
missing_twitter_followers         0.253  0.435  0.000  1.000
missing_ins_followers             0.087  0.281  0.000  1.000
missing_ycs_views                 0.088  0.284  0.000  1.000